# Generated by Django 4.1.4 on 2023-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price_uz', models.IntegerField()),
                ('price_eu', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
