# Generated by Django 4.1.4 on 2023-11-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edem', '0005_imageattachment_img_alter_course_title_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name=models.ImageField(upload_to=''))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edem.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='img',
            name='images',
        ),
        migrations.RemoveField(
            model_name='img',
            name='imageuploader_profile',
        ),
        migrations.DeleteModel(
            name='ImageAttachment',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
