# Generated by Django 4.1.4 on 2023-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edem', '0009_photo_image3_photo_image4_photo_image5_photo_image6_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image8',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
