# Generated by Django 4.1.4 on 2023-11-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edem', '0011_rename_image_photo_image1_photo_image2_photo_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='product',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image8',
        ),
    ]
