# Generated by Django 4.1.4 on 2023-12-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edem', '0012_rename_product_photo_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='beds',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='size_room',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
