# Generated by Django 4.2.1 on 2023-12-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edem', '0013_course_beds_course_size_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='standart-1.jpg', null=True, upload_to=''),
        ),
    ]
